// Generated by unplugin-env-parsing
export {}
declare global {
  interface ImportMetaEnv {
    readonly 'VITE_APP_CHAIN_ID': number
  }
  namespace NodeJS {
    interface ProcessEnv {
      readonly 'VITE_APP_CHAIN_ID': number
      readonly 'NVM_INC': string
      readonly 'TERM_PROGRAM': string
      readonly 'NODE': string
      readonly 'NVM_CD_FLAGS': string
      readonly 'PYENV_ROOT': string
      readonly 'INIT_CWD': string
      readonly 'ASDF_DIR': string
      readonly 'TERM': string
      readonly 'SHELL': string
      readonly 'HOMEBREW_REPOSITORY': string
      readonly 'TMPDIR': string
      readonly 'TERM_PROGRAM_VERSION': string
      readonly 'MallocNanoZone': number
      readonly 'ORIGINAL_XDG_CURRENT_DESKTOP': string
      readonly 'ZDOTDIR': string
      readonly 'TERM_SESSION_ID': string
      readonly 'NVM_DIR': string
      readonly 'USER': string
      readonly 'COMMAND_MODE': string
      readonly 'PNPM_SCRIPT_SRC_DIR': string
      readonly 'SSH_AUTH_SOCK': string
      readonly '__CF_USER_TEXT_ENCODING': string
      readonly 'PATH': string
      readonly '__CFBundleIdentifier': string
      readonly 'USER_ZDOTDIR': string
      readonly 'PWD': string
      readonly 'LANG': string
      readonly 'NODE_PATH': string
      readonly 'XPC_FLAGS': string
      readonly 'XPC_SERVICE_NAME': number
      readonly 'PYENV_SHELL': string
      readonly 'SHLVL': number
      readonly 'HOME': string
      readonly 'HOMEBREW_PREFIX': string
      readonly 'LOGNAME': string
      readonly 'LC_CTYPE': string
      readonly 'NVM_BIN': string
      readonly 'INFOPATH': string
      readonly 'HOMEBREW_CELLAR': string
      readonly 'GIT_ASKPASS': string
      readonly 'COLORTERM': string
      readonly 'NODE_ENV': string
    }
  }
}