// Generated by unplugin-env-parsing
export {}
declare global {
  interface ImportMetaEnv {
    readonly 'VITE_APP_CHAIN_ID': number
  }
  namespace NodeJS {
    interface ProcessEnv {
      readonly 'VITE_APP_CHAIN_ID': number
      readonly 'NVM_INC': string
      readonly 'MANPATH': string
      readonly 'STARSHIP_SHELL': string
      readonly 'TERM_PROGRAM': string
      readonly 'NODE': string
      readonly 'INIT_CWD': string
      readonly 'NVM_CD_FLAGS': string
      readonly '_P9K_TTY': string
      readonly 'SHELL': string
      readonly 'TERM': string
      readonly 'TMPDIR': string
      readonly 'HOMEBREW_REPOSITORY': string
      readonly 'TERM_PROGRAM_VERSION': string
      readonly 'MallocNanoZone': number
      readonly 'ORIGINAL_XDG_CURRENT_DESKTOP': string
      readonly 'ZDOTDIR': string
      readonly 'ZSH': string
      readonly 'USER': string
      readonly 'NVM_DIR': string
      readonly 'LS_COLORS': string
      readonly 'COMMAND_MODE': string
      readonly 'SSH_AUTH_SOCK': string
      readonly '__CF_USER_TEXT_ENCODING': string
      readonly 'PAGER': string
      readonly 'LSCOLORS': string
      readonly 'PATH': string
      readonly '_': string
      readonly '__CFBundleIdentifier': string
      readonly 'USER_ZDOTDIR': string
      readonly 'PWD': string
      readonly 'P9K_SSH': number
      readonly 'LANG': string
      readonly 'P9K_TTY': string
      readonly 'XPC_FLAGS': string
      readonly 'XPC_SERVICE_NAME': number
      readonly 'HOME': string
      readonly 'SHLVL': number
      readonly 'HOMEBREW_PREFIX': string
      readonly 'LOGNAME': string
      readonly 'LESS': string
      readonly 'STARSHIP_SESSION_KEY': number
      readonly 'YARN_WRAP_OUTPUT': boolean
      readonly 'NVM_BIN': string
      readonly 'HOMEBREW_CELLAR': string
      readonly 'INFOPATH': string
      readonly 'GIT_ASKPASS': string
      readonly '_P9K_SSH_TTY': string
      readonly 'COLORTERM': string
      readonly 'NODE_ENV': string
    }
  }
}